#gitlab-ci for the cookiecutter template
image: python:3.12-slim

variables:
  UV_CACHE_DIR: "$CI_PROJECT_DIR/.uv-cache"
  PRE_COMMIT_HOME: "$CI_PROJECT_DIR/.pre-commit-cache"

cache:
  key:
    files:
      - uv.lock
  paths:
    - .uv-cache/
    - .pre-commit-cache/

stages:
  - lint
  - test
  - docs

build:
  stage: lint
  before_script:
    - apt-get update && apt-get install -y git # required by pre-commit
    - pip install uv
    - uv sync
  script:
    - uv run pre-commit run --all-files

test:
  stage: test
  before_script:
    - pip install uv
    - uv sync
  script:
    - uv run pytest --cov=src
  coverage: '/TOTAL.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'

# docs:
#   stage: docs
#   before_script:
#     - pip install poetry
#     - poetry config virtualenvs.in-project true
#     - poetry install
#   script:
#     - apt-get update && apt-get install -y make
#     - make -C docs html
#     - mv build/sphinx/html/ public/
#   artifacts:
#     paths:
#     - public
#   rules:

include:
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Jobs/SAST.gitlab-ci.yml
  - template: Jobs/Secret-Detection.gitlab-ci.yml
